config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'overview#index'

  localized do
    namespace :send do
      root 'overview#index'
      get :navigate, to: 'navigate#index'
      get :capacities, to: 'capacities#index'
      resources :priorities
    end
    namespace :receive do
      root 'inboxes#show'
      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      get 'signup', to: 'recipients#new'
      get 'message/:id/delete', to: 'messages#destroy', as: 'delete_message'
      get 'settings', to: 'recipients#edit'
      patch 'settings', to: 'recipients#update'
      get 'rule/:id/delete', to: 'rules#destroy', as: 'delete_rule'
      resources :sessions
      resources :recipients
      resources :messages
      resources :rules
    end
    direct :create_recipients do
      { action: 'create', controller: 'receive/recipients' }
    end
  end
end

app/controllers/overview_controller.rb
# frozen_string_literal: true

class OverviewController < ApplicationController
end

app/controllers/send/overview_controller.rb
# frozen_string_literal: true

module Send
  class OverviewController < ApplicationController
    def index
      @recipient_address = params[:recipient]
    end
  end
end

app/controllers/sender/overview_controller.rb
# frozen_string_literal: true

module Sender
  class OverviewController < ApplicationController
    def index
      @recipient_address = params[:recipient]
    end
  end
end

app/views/overview/index.html.erb
<main class="overview">

  <div class="row mt-4">
    <div class="col-12">
      <h1>Willkommen bei Pay2Mail! Was möchten Sie tun?</h1>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-sm-6 mb-4">
      <%= link_to send_root_path, class: "link_wrapper" do %>
        <div class="card">
          <div class="card-body">
            <div class="overview__icon mb-3">
              <i class="bi bi-send p-2"></i>
            </div>
            <p class="overview__information">Ich bin Absender und möchte das Aufkommen meines Empfängers einsehen oder
              eine E-Mail versenden.</p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm-6 mb-4">
      <%= link_to receive_root_path, class: "link_wrapper" do %>
        <div class="card">
          <div class="card-body">
            <div class="overview__icon mb-3">
              <i class="bi bi-inbox p-2"></i>
            </div>
            <p class="overview__information">Ich bin Empfänger und möchte meinen Posteingang einsehen oder meine
              Bearbeitungsleistung anpassen.</p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</main>