config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'overview#index'

  localized do
    namespace :send do
      root 'overview#index'
      get :navigate, to: 'navigate#index'
      get :capacities, to: 'capacities#index'
      resources :priorities
    end
    namespace :receive do
      root 'inboxes#show'
      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      get 'signup', to: 'recipients#new'
      get 'message/:id/delete', to: 'messages#destroy', as: 'delete_message'
      get 'settings', to: 'recipients#edit'
      patch 'settings', to: 'recipients#update'
      get 'rule/:id/delete', to: 'rules#destroy', as: 'delete_rule'
      resources :sessions
      resources :recipients
      resources :messages
      resources :rules
    end
    direct :create_recipients do
      { action: 'create', controller: 'receive/recipients' }
    end
  end
end

app/models/rule.rb
# frozen_string_literal: true

class Rule < ApplicationRecord
  belongs_to :inbox
end

app/controllers/receive/inboxes_controller.rb
# frozen_string_literal: true

module Receive
  class InboxesController < ApplicationController
    before_action :authorize

    def show
      @inbox = params[:id].present? ? Inbox.find(params[:id]) : Inbox.find_by(recipient: current_user)
      EmailLoadJob.perform_now(recipients: [@inbox.recipient]) if params[:fetch].nil?
      @messages_due_today = @inbox.recipient.editing_performance_per_day - @inbox.messages.where(processed_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).size
      @due_dates = DueDateServices.due_dates(@inbox, @messages_due_today)
    end
  end
end

app/controllers/receive/messages_controller.rb
# frozen_string_literal: true

module Receive
  class MessagesController < ApplicationController
    before_action :authorize

    def show
      @message = Message.find(params[:id])
      @processable = (params[:due].present? && params[:due] == I18n.l(Time.now.to_date)) || (params[:ruled].present? && params[:ruled] == 'true')
    end

    def destroy
      message = Message.find(params[:id])
      if params[:fetch].nil?
        EmailServices.establish_connection(current_user.credential)
        EmailServices.read_message(message)
      end
      message.processed_at = params[:ruled] == 'true' ? Time.zone.parse('1900-01-01 00:00') : Time.now
      message.save
      redirect_to receive_root_path
    end
  end
end

app/controllers/receive/recipients_controller.rb
# frozen_string_literal: true

module Receive
  class RecipientsController < ApplicationController
    def new
      @recipient = Recipient.new
    end

    def create
      inbox = Inbox.new
      inbox.save
      @recipient = fill_recipient(params, inbox)
      credentials = fill_credentials(params)
      if @recipient.save
        credentials.recipient = @recipient
        credentials.save
        session[:recipient_id] = @recipient.id
        redirect_to receive_root_path
      else
        inbox.delete
        redirect_to receive_signup_path(error: true)
      end
    end

    def edit
      @recipient = current_user
    end

    def update
      @recipient = current_user
      @recipient.editing_performance_per_day = params[:recipient][:editing_performance_per_day]
      if @recipient.save
        redirect_to receive_root_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def fill_recipient(form_data, inbox)
      recipient = Recipient.new
      recipient.username = form_data[:username]
      recipient.password = form_data[:password]
      recipient.name = form_data[:name]
      recipient.email_address = form_data[:email_address]
      recipient.editing_performance_per_day = form_data[:editing_performance_per_day]
      recipient.inbox = inbox
      recipient
    end

    def fill_credentials(form_data)
      credential = Credential.new
      credential.server = form_data[:server]
      credential.port = form_data[:port]
      credential.ssl = form_data[:ssl]
      credential.auth_type = form_data[:auth_type]
      credential.username = form_data[:email_address]
      credential.password = form_data[:email_password]
      credential
    end
  end
end

app/controllers/receive/rules_controller.rb
# frozen_string_literal: true

module Receive
  class RulesController < ApplicationController
    before_action :authorize

    def index
      @rules = current_user.inbox.rules
    end

    def new
      @rule = Rule.new
    end

    def create
      rule = Rule.new
      rule.field_to_search = params[:rule][:field_to_search]
      rule.field_matcher = params[:rule][:field_matcher]
      rule.inbox = current_user.inbox
      if rule.save
        redirect_to receive_rules_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @rule = Rule.find(params[:id])
    end

    def update
      @rule = Rule.find(params[:id])
      @rule.field_to_search = params[:rule][:field_to_search]
      @rule.field_matcher = params[:rule][:field_matcher]
      if @rule.save
        redirect_to receive_rules_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      rule = Rule.find(params[:id])
      rule.delete
      redirect_to receive_rules_path
    end
  end
end

app/controllers/receive/sessions_controller.rb
# frozen_string_literal: true

module Receive
  class SessionsController < ApplicationController
    def new; end

    def create
      recipient = Recipient.find_by(username: params[:username])
      if recipient&.authenticate(params[:password])
        session[:recipient_id] = recipient.id
        redirect_to receive_root_url
      else
        redirect_to receive_login_path(error: 'true')
      end
    end

    def destroy
      session[:recipient_id] = nil
      redirect_to root_url
    end
  end
end

app/helpers/receive/rules_helper.rb
# frozen_string_literal: true

module Receive
  module RulesHelper
    def translate_field_to_search(value)
      case value
      when 'subject'
        'Betreff'
      when 'sender_address'
        'Adresse des Absenders'
      when 'content'
        'Inhalt der E-Mail'
      else
        ''
      end
    end
  end
end

app/views/receive/rules/_rule.html.erb
<%= link_to edit_receive_rule_path(rule), class: 'link_wrapper' do %>
  <div class="card col-sm-6 mb-2 p-2 rule">
    <div class="row" style="text-align: center">
      <div class="col-4"><%= translate_field_to_search(rule.field_to_search) %></div>
      <div class="col-4">enthält</div>
      <div class="col-4"><%= rule.field_matcher %></div>
    </div>
  </div>
  <div class="col-sm-6"></div>
<% end %>

app/views/receive/rules/edit.html.erb
<div class="row mt-4">
  <div class="col-12">
    <h1>Ausnahmeregel bearbeiten</h1>
  </div>
</div>

<%= form_with model: @rule, url: receive_rule_path, method: :patch, class: 'row mt-3 input-group' do |form| %>
  <div class="mb-3 mt-3 col-sm-3">
    <%= form.label :field_to_search, 'Zu durchsuchendes Feld' %>
    <%= form.select :field_to_search, options_for_select(
      [{ name: 'Betreff', id: 'subject' }, { name: 'Absenderadresse', id: 'sender_address' }, { name: 'Inhalt der Nachricht', id: 'content' }].map { |c| [c[:name], c[:id]] }, @rule.field_to_search),
                    {}, { class: 'form-select' } %>
  </div>
  <div class="mt-3 mb-3 col-sm-3">
    <%= form.label :field_matcher, 'Wert' %>
    <%= form.text_field :field_matcher, class: "form-control", value: @rule.field_matcher %>
  </div>
  <div class="col-sm-6">
  </div>
  <%= link_to 'Regel löschen', receive_delete_rule_path(@rule), class: 'col-sm-12 mb-3' %>
  <div class="col-sm-6">
    <%= form.submit 'Regel speichern', class: 'action' %>
  </div>
<% end %>

app/views/receive/rules/index.html.erb
<main class="rules">

  <div class="row mt-2">
    <%= link_to '← Zurück zu den Einstellungen', receive_settings_path, class: 'back-button' %>
  </div>

  <div class="row mt-4">
    <div class="col-12">
      <h1>Ausnahmeregeln</h1>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12">
      <p>Sie können Regeln definieren, nach welcher eine Nachricht als Ausnahme gilt und bereits vor ihrer Fälligkeit
        bearbeitet werden kann. Eine Regel besteht aus einem Feld, welches nach einem gegebenen Wert durchsucht wird.
        Mehrere Regeln werden mit ODER verknüpft.
        Beachten Sie, dass diese Nachrichten <strong>nicht</strong> zu Ihrer Bearbeitungsleistung
        zählen.</p>
    </div>
  </div>

  <div class="row mt-2">
    <%= link_to 'Neue Regel erstellen', new_receive_rule_path %>
  </div>

  <div class="row mt-4">
    <%= render @rules || 'Sie haben bisher keine Regeln erstellt' %>
  </div>

</main>

app/views/receive/rules/new.html.erb
<div class="row mt-4">
  <div class="col-12">
    <h1>Ausnahmeregel erstellen</h1>
  </div>
</div>

<%= form_with model: Rule.new, url: receive_rules_path, method: :post, class: 'row mt-3 input-group' do |form| %>
  <div class="mb-3 mt-3 col-sm-3">
    <%= form.label :field_to_search, 'Zu durchsuchendes Feld' %>
    <%= form.select :field_to_search, options_for_select(
      [{ name: 'Betreff', id: 'subject' }, { name: 'Absenderadresse', id: 'sender_address' }, { name: 'Inhalt der Nachricht', id: 'content' }].map { |c| [c[:name], c[:id]] }),
                    {}, { class: 'form-select' } %>
  </div>
  <div class="mt-3 mb-3 col-sm-3">
    <%= form.label :field_matcher, 'Wert' %>
    <%= form.text_field :field_matcher, class: "form-control" %>
  </div>
  <div class="col-sm-6">
  </div>
  <div class="col-sm-6">
    <%= form.submit 'Regel speichern', class: 'action' %>
  </div>
<% end %>