config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'overview#index'

  localized do
    namespace :send do
      root 'overview#index'
      get :navigate, to: 'navigate#index'
      get :capacities, to: 'capacities#index'
      resources :priorities
    end
    namespace :receive do
      root 'inboxes#show'
      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      get 'signup', to: 'recipients#new'
      get 'message/:id/delete', to: 'messages#destroy', as: 'delete_message'
      get 'settings', to: 'recipients#edit'
      patch 'settings', to: 'recipients#update'
      get 'rule/:id/delete', to: 'rules#destroy', as: 'delete_rule'
      resources :sessions
      resources :recipients
      resources :messages
      resources :rules
    end
    direct :create_recipients do
      { action: 'create', controller: 'receive/recipients' }
    end
  end
end

app/controllers/send/capacities_controller.rb
# frozen_string_literal: true

module Send
  class CapacitiesController < ApplicationController
    before_action :fetch_recipient

    def index
      if @recipient.present?
        inbox = Inbox.find_by(recipient: @recipient)
        @mails_count = Message.unprocessed.where(inbox: inbox).length
        @editing_performance = @recipient.editing_performance_per_day
        messages_due_today = @recipient.editing_performance_per_day - inbox.messages.where(processed_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).size
        due_dates = DueDateServices.due_dates(inbox, messages_due_today)
        @target_date = due_dates[-1] += 1
      else
        render 'send/static/404', status: 404
      end
    end

    def fetch_recipient
      recipient_address = params[:recipient]
      @recipient = Recipient.find_by(email_address: recipient_address)
      EmailLoadJob.perform_now(recipients: [@recipient]) if @recipient.present? && params[:fetch].nil?
    end
  end
end

app/controllers/send/navigate_controller.rb
# frozen_string_literal: true

module Send
  class NavigateController < ApplicationController
    def index
      case params[:commit]
      when 'E-Mail priorisieren'
        redirect_to controller: :priorities, action: 'index', recipient: params[:recipient]
      when 'Aufkommen einsehen'
        redirect_to controller: :capacities, action: 'index', recipient: params[:recipient]
      else
        redirect_to controller: :overview, action: 'index', recipient: params[:recipient]
      end
    end
  end
end

app/controllers/send/overview_controller.rb
# frozen_string_literal: true

module Send
  class OverviewController < ApplicationController
    def index
      @recipient_address = params[:recipient]
    end
  end
end

app/controllers/send/priorities_controller.rb
# frozen_string_literal: true

module Send
  class PrioritiesController < ApplicationController
    before_action :fetch_recipient

    def index
      if @recipient.present?
        inbox = Inbox.find_by(recipient: @recipient)
        messages_due_today = @recipient.editing_performance_per_day - inbox.messages.where(processed_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).size
        @messages_sorted = Message.unprocessed.where(inbox: inbox).with_value(sorted: true)
        @due_dates = DueDateServices.due_dates(inbox, messages_due_today)
      else
        render 'send/static/404'
      end
    end

    def create
      form_data = params[:value]
      value = Value.new
      value.sender_address = form_data[:sender_address]
      value.recipient_address = form_data[:recipient_address]
      value.amount = form_data[:amount]
      value.save
      redirect_to send_priority_path(value.uuid, target: value.target_date)
    end

    def show
      @uuid = params[:id]
    end

    def fetch_recipient
      recipient_address = params[:recipient]
      @recipient = Recipient.find_by(email_address: recipient_address)
      EmailLoadJob.perform_now(recipients: [@recipient]) if @recipient.present? && params[:fetch].nil?
    end
  end
end

app/controllers/sender/capacities_controller.rb
# frozen_string_literal: true

module Sender
  class CapacitiesController < ApplicationController
    before_action :fetch_recipient

    def index
      if @recipient.present?
        inbox = Inbox.find_by(recipient: @recipient)
        @mails_count = Message.where(inbox: inbox).length
        @editing_performance = @recipient.editing_performance_per_day
        @target_date = (@mails_count / @editing_performance + 1).to_f.ceil.days.from_now.to_date
      else
        render 'sender/static/404', status: 404
      end
    end

    def fetch_recipient
      recipient_address = params[:recipient]
      @recipient = Recipient.find_by(email_address: recipient_address)
      EmailLoadJob.perform_now(recipients: [@recipient]) if @recipient.present? && params[:fetch].nil?
    end
  end
end

app/views/send/capacities/index.html.erb
<main class="capacities">

  <div class="row mt-4">
    <div class="col-12">
      <h1>E-Mail Aufkommen von <%= @recipient.name %></h1>
    </div>
  </div>

  <% if @mails_count > 50 %>
    <div class="row mt-4">
      <div class="col-12">
        <div class="alert alert-warning" role="alert">
          Hinweis: <%= @recipient.email_address %> hat aktuell ein erhöhtes E-Mail Aufkommen, was zu einer Verzögerung in der
          Bearbeitung führen kann.
        </div>
      </div>
    </div>
  <% end %>

  <div class="row mt-4">
    <div class="col-sm-4 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="capacities__icon mb-3">
            <i class="bi bi-inbox p-2"></i>
          </div>
          <p class="capacities__information"><%= @recipient.name %> hat aktuell <%= @mails_count %> unbearbeitete E-Mails
            offen.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-4 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="capacities__icon mb-3">
            <i class="bi bi-bar-chart-steps p-2"></i>
          </div>
          <p class="capacities__information"><%= @recipient.name %> bearbeitet mindestens <%= @editing_performance %> E-Mails pro
            Tag.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-4 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="capacities__icon mb-3">
            <i class="bi bi-calendar-event p-2"></i>
          </div>
          <p class="capacities__information">Würden Sie jetzt eine E-Mail absenden, würde sie spätestens
            am <%= l @target_date %> beantwortet werden.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-5 mb-5">
    <div class="col-12" style="text-align: center">
      <h2>Soll Ihre E-Mail schneller bearbeitet werden?</h2>
      <p>Dann priorisieren Sie Ihre E-Mail mit Pay2Mail in wenigen Schritten.</p>
      <%= link_to "E-Mail priorisieren", send_priorities_path(:recipient => @recipient.email_address), class: "btn btn-primary" %>
    </div>
  </div>

</main>