config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  root 'overview#index'

  localized do
    namespace :send do
      root 'overview#index'
      get :navigate, to: 'navigate#index'
      get :capacities, to: 'capacities#index'
      resources :priorities
    end
    namespace :receive do
      root 'inboxes#show'
      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      get 'signup', to: 'recipients#new'
      get 'message/:id/delete', to: 'messages#destroy', as: 'delete_message'
      get 'settings', to: 'recipients#edit'
      patch 'settings', to: 'recipients#update'
      get 'rule/:id/delete', to: 'rules#destroy', as: 'delete_rule'
      resources :sessions
      resources :recipients
      resources :messages
      resources :rules
    end
    direct :create_recipients do
      { action: 'create', controller: 'receive/recipients' }
    end
  end
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :inbox
  scope :processed, -> { where.not(processed_at: nil) }
  scope :unprocessed, -> { where(processed_at: nil) }
  scope :matches_rules, lambda {
    results = []
    if first.present?
      rules = first.inbox.rules
      rules.each do |rule|
        results << where(Message.arel_table[rule.field_to_search].matches("%#{rule.field_matcher}%")).to_a
      end
      results.flatten.uniq.sort_by { |e| e[:send_at] }
    else
      results
    end
  }

  def value
    value = Value.find_by(uuid: value_header)
    value.present? ? value.amount : 0
  end

  def self.with_value(sorted: false)
    messages = all
    messages.each do |message|
      latest_value_creation = message.send_at + 30.minutes
      value = Value.where(
        uuid: message.value_header,
        recipient_address: message.recipient_address,
        sender_address: message.sender_address,
        created_at: ..latest_value_creation
      ).first

      next if message.value_header.nil? || value.nil?

      message.value_header = value.amount
    end
    if sorted
      sort_by_value(messages)
    else
      messages
    end
  end

  def self.group_by_amount(editing_performance)
    messages_valued = with_value(sorted: true)
    messages_grouped = []
    current_group = []
    messages_valued.each_with_index do |message, i|
      current_group << message
      if ((i + 1) % editing_performance).zero?
        messages_grouped << current_group
        current_group = []
      end
    end
    messages_grouped << current_group if messages_valued.length % editing_performance != 0
    messages_grouped
  end

  def self.sort_by_value(messages)
    messages.sort_by do |x|
      [x.value_header.to_i, -x.send_at.to_i]
    end.reverse
  end
end

app/controllers/receive/inboxes_controller.rb
# frozen_string_literal: true

module Receive
  class InboxesController < ApplicationController
    before_action :authorize

    def show
      @inbox = params[:id].present? ? Inbox.find(params[:id]) : Inbox.find_by(recipient: current_user)
      EmailLoadJob.perform_now(recipients: [@inbox.recipient]) if params[:fetch].nil?
      @messages_due_today = @inbox.recipient.editing_performance_per_day - @inbox.messages.where(processed_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).size
      @due_dates = DueDateServices.due_dates(@inbox, @messages_due_today)
    end
  end
end

app/controllers/receive/messages_controller.rb
# frozen_string_literal: true

module Receive
  class MessagesController < ApplicationController
    before_action :authorize

    def show
      @message = Message.find(params[:id])
      @processable = (params[:due].present? && params[:due] == I18n.l(Time.now.to_date)) || (params[:ruled].present? && params[:ruled] == 'true')
    end

    def destroy
      message = Message.find(params[:id])
      if params[:fetch].nil?
        EmailServices.establish_connection(current_user.credential)
        EmailServices.read_message(message)
      end
      message.processed_at = params[:ruled] == 'true' ? Time.zone.parse('1900-01-01 00:00') : Time.now
      message.save
      redirect_to receive_root_path
    end
  end
end

app/controllers/receive/recipients_controller.rb
# frozen_string_literal: true

module Receive
  class RecipientsController < ApplicationController
    def new
      @recipient = Recipient.new
    end

    def create
      inbox = Inbox.new
      inbox.save
      @recipient = fill_recipient(params, inbox)
      credentials = fill_credentials(params)
      if @recipient.save
        credentials.recipient = @recipient
        credentials.save
        session[:recipient_id] = @recipient.id
        redirect_to receive_root_path
      else
        inbox.delete
        redirect_to receive_signup_path(error: true)
      end
    end

    def edit
      @recipient = current_user
    end

    def update
      @recipient = current_user
      @recipient.editing_performance_per_day = params[:recipient][:editing_performance_per_day]
      if @recipient.save
        redirect_to receive_root_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def fill_recipient(form_data, inbox)
      recipient = Recipient.new
      recipient.username = form_data[:username]
      recipient.password = form_data[:password]
      recipient.name = form_data[:name]
      recipient.email_address = form_data[:email_address]
      recipient.editing_performance_per_day = form_data[:editing_performance_per_day]
      recipient.inbox = inbox
      recipient
    end

    def fill_credentials(form_data)
      credential = Credential.new
      credential.server = form_data[:server]
      credential.port = form_data[:port]
      credential.ssl = form_data[:ssl]
      credential.auth_type = form_data[:auth_type]
      credential.username = form_data[:email_address]
      credential.password = form_data[:email_password]
      credential
    end
  end
end

app/controllers/receive/rules_controller.rb
# frozen_string_literal: true

module Receive
  class RulesController < ApplicationController
    before_action :authorize

    def index
      @rules = current_user.inbox.rules
    end

    def new
      @rule = Rule.new
    end

    def create
      rule = Rule.new
      rule.field_to_search = params[:rule][:field_to_search]
      rule.field_matcher = params[:rule][:field_matcher]
      rule.inbox = current_user.inbox
      if rule.save
        redirect_to receive_rules_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @rule = Rule.find(params[:id])
    end

    def update
      @rule = Rule.find(params[:id])
      @rule.field_to_search = params[:rule][:field_to_search]
      @rule.field_matcher = params[:rule][:field_matcher]
      if @rule.save
        redirect_to receive_rules_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      rule = Rule.find(params[:id])
      rule.delete
      redirect_to receive_rules_path
    end
  end
end

app/controllers/receive/sessions_controller.rb
# frozen_string_literal: true

module Receive
  class SessionsController < ApplicationController
    def new; end

    def create
      recipient = Recipient.find_by(username: params[:username])
      if recipient&.authenticate(params[:password])
        session[:recipient_id] = recipient.id
        redirect_to receive_root_url
      else
        redirect_to receive_login_path(error: 'true')
      end
    end

    def destroy
      session[:recipient_id] = nil
      redirect_to root_url
    end
  end
end

app/helpers/receive/rules_helper.rb
# frozen_string_literal: true

module Receive
  module RulesHelper
    def translate_field_to_search(value)
      case value
      when 'subject'
        'Betreff'
      when 'sender_address'
        'Adresse des Absenders'
      when 'content'
        'Inhalt der E-Mail'
      else
        ''
      end
    end
  end
end

app/views/receive/messages/show.html.erb
<main class="messages">

  <div class="row mt-2">
    <%= link_to '← Zurück zum Posteingang', receive_root_path, class: 'back-button' %>
  </div>

  <div class="row mt-4">
    <div class="col-12">
      <h2>Nachricht von <%= @message.sender_address %></h2>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-12">
      <p>Bearbeiten Sie die nachfolgende Nachricht in Ihrem E-Mail Client und klicken Sie daraufhin auf "Erledigt".</p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-12" title="<%= "Sie können nur Nachrichten bearbeiten, die heute fällig sind." unless @processable %>">
        <%= link_to 'Erledigt', receive_delete_message_path(@message.id, ruled: params[:ruled]), class: "d-block d-sm-none btn btn-success mb-3 #{'disabled' unless @processable}" %>
      <div class="card">
        <div class="p-3 small messages__metadata">
          <div class="row">
            <div class="col-sm-10">
              <p><strong>Empfangen:</strong> <%= l(@message.send_at, format: '%d.%m.%Y, %H:%M') %></p>
              <p><strong>Von:</strong> <%= @message.sender_address %></p>
              <p><strong>An:</strong> <%= @message.recipient_address %></p>
              <p><strong>Betreff:</strong> <%= @message.subject %></p>
              <p><strong>Gezahlt:</strong> <%= format_value_amount(@message.value) %></p>
              <% if params[:due].present? %><p><strong>Fällig:</strong> <%= params[:due] %></p>
              <% end %>
            </div>
            <div class="col-sm-2" title="<%= "Sie können nur Nachrichten bearbeiten, die heute fällig sind." unless @processable %>">
                <%= link_to 'Erledigt', receive_delete_message_path(@message.id, ruled: params[:ruled]), class: "d-none d-sm-block btn btn-success #{'disabled' unless @processable}" %>
            </div>
          </div>
        </div>
        <% if @message.multipart? %>
          <iframe height="500" srcdoc="<%= h @message.content %>"></iframe>
        <% else %>
          <div class="p-3 messages__content"><%= simple_format @message.content %></div>
        <% end %>
      </div>
    </div>
  </div>
</main>